name: The Rites of Deployment aka CD

on:
  workflow_run:
    workflows: [The Trial of Truth aka CI]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Retrieving the Sacred Artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: the-edge-awakened
          path: ./.svelte-kit/cloudflare
          search_artifacts: true

      - name: Download Wrangler Configuration
        uses: dawidd6/action-download-artifact@v6
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: the-edge-config
          path: ./
          search_artifacts: true

      - name: Invoking the Cloudflare Spirits
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy
          preCommands: |
            echo "${{ secrets.TRAKT_CLIENT_ID }}" | npx wrangler pages secret put TRAKT_CLIENT_ID
            echo "${{ secrets.TRAKT_CLIENT_SECRET }}" | npx wrangler pages secret put TRAKT_CLIENT_SECRET
